version: "3"
tasks:
  protoc:
    cmds:
      - protoc
        --proto_path=internal/adapter/inbound/grpc/protoc
        --go_out=internal/adapter/inbound/grpc/generated
        --go_opt=paths=source_relative
        --go-grpc_out=internal/adapter/inbound/grpc/generated
        --go-grpc_opt=paths=source_relative
        internal/adapter/inbound/grpc/protoc/**/*.proto
      - go mod tidy

  get-orgs:
    - cp "./../nft-deploy/docker/orgs.json" "./deploy/orgs.json"

  dltclient:
    - curl -o "./internal/adapter/inbound/dlt/combined.json" https://raw.githubusercontent.com/pramod-shenkar/nft-chain/refs/heads/master/build/json/combined.json
    - abigen
      --combined-json "./internal/adapter/inbound/dlt/combined.json"
      --pkg dlt
      --out "./internal/adapter/inbound/dlt/combined.go"
